/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Agustin Bertuzzi (https://sketchfab.com/agusbm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guitarra-20-38f24c1eb8ae44d5bf2a4f9b940c96ec
Title: Guitarra 2.0
*/
'use client'
import { useAnimations, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		polySurface4_fusta_amb_barnis_0: THREE.Mesh
		polySurface2_fusta_amb_barnis_0: THREE.Mesh
		polySurface2_fusta_davantera_0: THREE.Mesh
		pPlane4_fusta_amb_barnis_0: THREE.Mesh
		pCube1_mastil_davanter_0: THREE.Mesh
		pCube2_trastes_0: THREE.Mesh
		pCube3_trastes_0: THREE.Mesh
		pCube4_trastes_0: THREE.Mesh
		pCube5_trastes_0: THREE.Mesh
		pCube6_trastes_0: THREE.Mesh
		pCube7_trastes_0: THREE.Mesh
		pCube8_trastes_0: THREE.Mesh
		pCube9_trastes_0: THREE.Mesh
		pCube10_trastes_0: THREE.Mesh
		pCube11_trastes_0: THREE.Mesh
		pCube12_trastes_0: THREE.Mesh
		pCube13_trastes_0: THREE.Mesh
		pCube14_trastes_0: THREE.Mesh
		pCube15_trastes_0: THREE.Mesh
		pCube16_trastes_0: THREE.Mesh
		pCube17_trastes_0: THREE.Mesh
		pCube18_trastes_0: THREE.Mesh
		pCube19_trastes_0: THREE.Mesh
		pCube20_trastes_0: THREE.Mesh
		pCube21_plastic_pont_0: THREE.Mesh
		pPlane9_plastic_pont_0: THREE.Mesh
		pPlane10_plastic_pont_0: THREE.Mesh
		pCube22_plastic_blanc_0: THREE.Mesh
		polySurface5_cargols_0: THREE.Mesh
		polySurface6_cargols_0: THREE.Mesh
		polySurface7_cargols_0: THREE.Mesh
		polySurface8_cargols_0: THREE.Mesh
		pCylinder6_cargols_0: THREE.Mesh
		pCylinder7_cargols_0: THREE.Mesh
		pPlane11_cargols_0: THREE.Mesh
		pCube23_clavijas_0: THREE.Mesh
		pCube23_clavijas_0_1: THREE.Mesh
		pPlane11_cargols_0_1: THREE.Mesh
		pCube23_clavijas_0_2: THREE.Mesh
		pPlane11_cargols_0_2: THREE.Mesh
		pPlane13_cargols_0: THREE.Mesh
		pCube25_clavijas_0: THREE.Mesh
		pCube23_clavijas_0_3: THREE.Mesh
		pPlane11_cargols_0_3: THREE.Mesh
		pPlane14_cargols_0: THREE.Mesh
		pCube26_clavijas_0: THREE.Mesh
		pCylinder8_plastic_blanc_0: THREE.Mesh
		pCylinder9_plastic_blanc_0: THREE.Mesh
		pCylinder10_plastic_blanc_0: THREE.Mesh
		pCylinder11_plastic_blanc_0: THREE.Mesh
		pCylinder12_plastic_blanc_0: THREE.Mesh
		pCylinder13_plastic_blanc_0: THREE.Mesh
		pCube24_plastic_blanc_0: THREE.Mesh
		pSphere12_trastes_0: THREE.Mesh
		pSphere10_trastes_0: THREE.Mesh
		pSphere9_trastes_0: THREE.Mesh
		pSphere8_trastes_0: THREE.Mesh
		pSphere7_trastes_0: THREE.Mesh
		pCylinder20_cordes_0: THREE.Mesh
		polySurface11_cordes_0: THREE.Mesh
		polySurface12_cordes_0: THREE.Mesh
		polySurface13_cordes_0: THREE.Mesh
		pCylinder22_cordes_0: THREE.Mesh
		pSphere11_trastes_0: THREE.Mesh
		polySurface9_cordes_0: THREE.Mesh
	}
	materials: {
		fusta_amb_barnis: THREE.MeshStandardMaterial
		fusta_davantera: THREE.MeshStandardMaterial
		mastil_davanter: THREE.MeshStandardMaterial
		trastes: THREE.MeshStandardMaterial
		plastic_pont: THREE.MeshStandardMaterial
		plastic_blanc: THREE.MeshStandardMaterial
		cargols: THREE.MeshStandardMaterial
		clavijas: THREE.MeshStandardMaterial
		cordes: THREE.MeshStandardMaterial
	}
}

type ActionName = 'Take 001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Guitar(props: JSX.IntrinsicElements['group']) {
	const group = useRef<THREE.Group | null>(null)
	const { nodes, materials, animations } = useGLTF(
		'/assets/models/guitarra_2.0.glb'
	) as unknown as GLTFResult
	const { actions } = useAnimations(animations as THREE.AnimationClip[], group)

	useFrame((state, delta, xrFrame) => {
		if (group.current != null)
			group.current.position.y = 0.5 + Math.sin(state.clock.elapsedTime) * 0.15
	})

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
			position={[0, 0.5, 0]}
			scale={[0.3, 0.3, 0.3]}
			rotation={[-0.1, -0.25, 0]}>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					rotation={[-Math.PI / 2, 0, 0]}>
					<group
						name="610f28b1a3a6412b8281784014549d95fbx"
						rotation={[Math.PI / 2, 0, 0]}>
						<group name="Object_2">
							<group name="RootNode">
								<group
									name="imagePlane1"
									position={[0, 0, -34.051]}
								/>
								<group
									name="imagePlane2"
									position={[-13.179, 0, 0]}
									rotation={[0, Math.PI / 2, 0]}
								/>
								<group name="pCylinder3">
									<group name="polySurface1">
										<group name="polySurface4">
											<mesh
												name="polySurface4_fusta_amb_barnis_0"
												geometry={
													nodes.polySurface4_fusta_amb_barnis_0.geometry
												}
												material={materials.fusta_amb_barnis}
											/>
										</group>
									</group>
								</group>
								<group name="polySurface2">
									<mesh
										name="polySurface2_fusta_amb_barnis_0"
										geometry={nodes.polySurface2_fusta_amb_barnis_0.geometry}
										material={materials.fusta_amb_barnis}
									/>
									<mesh
										name="polySurface2_fusta_davantera_0"
										geometry={nodes.polySurface2_fusta_davantera_0.geometry}
										material={materials.fusta_davantera}
									/>
								</group>
								<group
									name="pPlane4"
									position={[-0.007, -0.014, 0]}>
									<mesh
										name="pPlane4_fusta_amb_barnis_0"
										geometry={nodes.pPlane4_fusta_amb_barnis_0.geometry}
										material={materials.fusta_amb_barnis}
									/>
								</group>
								<group
									name="pCube1"
									position={[0.167, 1.122, 0.706]}
									scale={[0.715, 6.258, 0.162]}>
									<mesh
										name="pCube1_mastil_davanter_0"
										geometry={nodes.pCube1_mastil_davanter_0.geometry}
										material={materials.mastil_davanter}
									/>
								</group>
								<group
									name="pCube2"
									position={[0.168, 3.751, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube2_trastes_0"
										geometry={nodes.pCube2_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube3"
									position={[0.166, 3.272, 0.693]}
									scale={[0.736, 0.04, 0.04]}>
									<mesh
										name="pCube3_trastes_0"
										geometry={nodes.pCube3_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube4"
									position={[0.166, 2.81, 0.693]}
									scale={[0.749, 0.04, 0.04]}>
									<mesh
										name="pCube4_trastes_0"
										geometry={nodes.pCube4_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube5"
									position={[0.168, 2.39, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube5_trastes_0"
										geometry={nodes.pCube5_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube6"
									position={[0.166, 1.993, 0.693]}
									scale={[0.769, 0.04, 0.04]}>
									<mesh
										name="pCube6_trastes_0"
										geometry={nodes.pCube6_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube7"
									position={[0.166, 1.611, 0.694]}
									scale={[0.779, 0.04, 0.04]}>
									<mesh
										name="pCube7_trastes_0"
										geometry={nodes.pCube7_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube8"
									position={[0.169, 1.252, 0.694]}
									scale={[0.795, 0.04, 0.04]}>
									<mesh
										name="pCube8_trastes_0"
										geometry={nodes.pCube8_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube9"
									position={[0.125, 0.914, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube9_trastes_0"
										geometry={nodes.pCube9_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube10"
									position={[0.168, 0.59, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube10_trastes_0"
										geometry={nodes.pCube10_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube11"
									position={[0.168, 0.292, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube11_trastes_0"
										geometry={nodes.pCube11_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube12"
									position={[0.168, 0.013, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube12_trastes_0"
										geometry={nodes.pCube12_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube13"
									position={[0.168, -0.271, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube13_trastes_0"
										geometry={nodes.pCube13_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube14"
									position={[0.168, -0.515, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube14_trastes_0"
										geometry={nodes.pCube14_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube15"
									position={[0.168, -0.76, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube15_trastes_0"
										geometry={nodes.pCube15_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube16"
									position={[0.168, -0.986, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube16_trastes_0"
										geometry={nodes.pCube16_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube17"
									position={[0.168, -1.195, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube17_trastes_0"
										geometry={nodes.pCube17_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube18"
									position={[0.168, -1.393, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube18_trastes_0"
										geometry={nodes.pCube18_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube19"
									position={[0.168, -1.584, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube19_trastes_0"
										geometry={nodes.pCube19_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube20"
									position={[0.168, -1.728, 0.693]}
									scale={[0.716, 0.04, 0.04]}>
									<mesh
										name="pCube20_trastes_0"
										geometry={nodes.pCube20_trastes_0.geometry}
										material={materials.trastes}
									/>
								</group>
								<group
									name="pCube21"
									position={[0.189, -5.004, 0.568]}
									scale={[2.497, 0.381, 0.141]}>
									<mesh
										name="pCube21_plastic_pont_0"
										geometry={nodes.pCube21_plastic_pont_0.geometry}
										material={materials.plastic_pont}
									/>
								</group>
								<group
									name="pPlane9"
									position={[-0.725, 4.067, 0.467]}
									rotation={[-0.262, 0, -0.031]}
									scale={[0.576, 0.361, 0.189]}>
									<mesh
										name="pPlane9_plastic_pont_0"
										geometry={nodes.pPlane9_plastic_pont_0.geometry}
										material={materials.plastic_pont}
									/>
								</group>
								<group
									name="pPlane10"
									position={[0.969, 6.729, -0.246]}
									rotation={[-0.262, 0, -3.113]}
									scale={[0.576, 0.361, 0.189]}>
									<mesh
										name="pPlane10_plastic_pont_0"
										geometry={nodes.pPlane10_plastic_pont_0.geometry}
										material={materials.plastic_pont}
									/>
								</group>
								<group
									name="pCube22"
									position={[0.172, 4.264, 0.657]}
									scale={[0.721, 0.035, 0.064]}>
									<mesh
										name="pCube22_plastic_blanc_0"
										geometry={nodes.pCube22_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="pCylinder4"
									position={[0, 3.458, -2.611]}
									scale={[0.073, 0.021, 0.073]}>
									<group name="transform2" />
								</group>
								<group
									name="pPlane12"
									position={[0.002, 3.471, -2.61]}
									rotation={[0, 0.262, 0]}
									scale={0.097}>
									<group name="transform1" />
								</group>
								<group
									name="pCylinder5"
									position={[-1.324, 5.808, 1.578]}
									rotation={[0, 0, -1.606]}
									scale={0.577}>
									<group name="polySurface5">
										<mesh
											name="polySurface5_cargols_0"
											geometry={nodes.polySurface5_cargols_0.geometry}
											material={materials.cargols}
										/>
									</group>
									<group
										name="polySurface6"
										position={[-0.053, 0.562, 0.001]}>
										<mesh
											name="polySurface6_cargols_0"
											geometry={nodes.polySurface6_cargols_0.geometry}
											material={materials.cargols}
										/>
									</group>
									<group name="transform3" />
									<group
										name="polySurface7"
										position={[0.698, 0.613, 0.219]}>
										<mesh
											name="polySurface7_cargols_0"
											geometry={nodes.polySurface7_cargols_0.geometry}
											material={materials.cargols}
										/>
									</group>
									<group
										name="polySurface8"
										position={[1.478, 0.665, 0.44]}>
										<mesh
											name="polySurface8_cargols_0"
											geometry={nodes.polySurface8_cargols_0.geometry}
											material={materials.cargols}
										/>
									</group>
								</group>
								<group
									name="pCylinder6"
									position={[-1.338, 5.396, 1.696]}
									rotation={[0, 0, -1.606]}
									scale={0.577}>
									<mesh
										name="pCylinder6_cargols_0"
										geometry={nodes.pCylinder6_cargols_0.geometry}
										material={materials.cargols}
									/>
								</group>
								<group
									name="pCylinder7"
									position={[-1.352, 4.939, 1.818]}
									rotation={[0, 0, -1.606]}
									scale={0.577}>
									<mesh
										name="pCylinder7_cargols_0"
										geometry={nodes.pCylinder7_cargols_0.geometry}
										material={materials.cargols}
									/>
								</group>
								<group
									name="group1"
									position={[0.528, 3.816, -2.573]}
									rotation={[1.309, 1.57, 0]}
									scale={0.493}>
									<group name="group2" />
									<group
										name="group3"
										position={[-0.862, 0.016, -0.029]}
									/>
									<group
										name="group4"
										position={[-1.821, 0.016, -0.059]}>
										<group name="group5" />
										<group
											name="group6"
											position={[-0.015, 0.01, -1.99]}>
											<group
												name="group9"
												position={[0.014, 0.002, 0.002]}
											/>
										</group>
										<group
											name="group7"
											position={[0.95, 0.01, -2.018]}
										/>
										<group
											name="group8"
											position={[1.863, 0.01, -2.044]}
										/>
									</group>
									<group name="group16">
										<group
											name="pPlane11"
											position={[2.503, 6.219, 0.312]}
											rotation={[0, 0, Math.PI / 2]}
											scale={0.241}>
											<mesh
												name="pPlane11_cargols_0"
												geometry={nodes.pPlane11_cargols_0.geometry}
												material={materials.cargols}
											/>
										</group>
										<group
											name="pCube23"
											position={[2.539, 5.792, 0.312]}
											scale={[0.346, 0.197, 0.151]}>
											<mesh
												name="pCube23_clavijas_0"
												geometry={nodes.pCube23_clavijas_0.geometry}
												material={materials.clavijas}
											/>
										</group>
									</group>
									<group
										name="group17"
										position={[0.045, 0.012, -2.101]}>
										<group name="group18">
											<group
												name="pCube23_1"
												position={[2.539, 5.792, 0.312]}
												scale={[0.346, 0.197, 0.151]}>
												<mesh
													name="pCube23_clavijas_0_1"
													geometry={nodes.pCube23_clavijas_0_1.geometry}
													material={materials.clavijas}
												/>
											</group>
											<group
												name="pPlane11_1"
												position={[2.503, 6.219, 0.312]}
												rotation={[0, 0, Math.PI / 2]}
												scale={0.241}>
												<mesh
													name="pPlane11_cargols_0_1"
													geometry={nodes.pPlane11_cargols_0_1.geometry}
													material={materials.cargols}
												/>
											</group>
										</group>
										<group
											name="group19"
											position={[-1.413, -0.379, 0]}>
											<group
												name="group20"
												position={[0.494, 0.422, 0]}>
												<group name="group21">
													<group
														name="pCube23_2"
														position={[2.541, 5.784, 0.336]}
														scale={[0.346, 0.197, 0.151]}>
														<mesh
															name="pCube23_clavijas_0_2"
															geometry={nodes.pCube23_clavijas_0_2.geometry}
															material={materials.clavijas}
														/>
													</group>
													<group
														name="pPlane11_2"
														position={[2.505, 6.211, 0.336]}
														rotation={[0, 0, Math.PI / 2]}
														scale={0.241}>
														<mesh
															name="pPlane11_cargols_0_2"
															geometry={nodes.pPlane11_cargols_0_2.geometry}
															material={materials.cargols}
														/>
													</group>
													<group
														name="pPlane13"
														position={[2.512, 6.197, 2.386]}
														rotation={[0, 0, Math.PI / 2]}
														scale={0.241}>
														<mesh
															name="pPlane13_cargols_0"
															geometry={nodes.pPlane13_cargols_0.geometry}
															material={materials.cargols}
														/>
													</group>
													<group
														name="pCube25"
														position={[2.548, 5.77, 2.386]}
														scale={[0.346, 0.197, 0.151]}>
														<mesh
															name="pCube25_clavijas_0"
															geometry={nodes.pCube25_clavijas_0.geometry}
															material={materials.clavijas}
														/>
													</group>
												</group>
												<group
													name="group22"
													position={[-0.958, 0.001, 0]}>
													<group
														name="group23"
														position={[0.006, 0.022, 0.144]}>
														<group
															name="pCube23_3"
															position={[2.543, 5.776, 0.22]}
															scale={[0.346, 0.197, 0.151]}>
															<mesh
																name="pCube23_clavijas_0_3"
																geometry={nodes.pCube23_clavijas_0_3.geometry}
																material={materials.clavijas}
															/>
														</group>
														<group
															name="pPlane11_3"
															position={[2.507, 6.203, 0.22]}
															rotation={[0, 0, Math.PI / 2]}
															scale={0.241}>
															<mesh
																name="pPlane11_cargols_0_3"
																geometry={nodes.pPlane11_cargols_0_3.geometry}
																material={materials.cargols}
															/>
														</group>
														<group
															name="pPlane14"
															position={[2.504, 6.184, 2.21]}
															rotation={[0, 0, Math.PI / 2]}
															scale={0.241}>
															<mesh
																name="pPlane14_cargols_0"
																geometry={nodes.pPlane14_cargols_0.geometry}
																material={materials.cargols}
															/>
														</group>
														<group
															name="pCube26"
															position={[2.54, 5.757, 2.211]}
															scale={[0.346, 0.197, 0.151]}>
															<mesh
																name="pCube26_clavijas_0"
																geometry={nodes.pCube26_clavijas_0.geometry}
																material={materials.clavijas}
															/>
														</group>
													</group>
												</group>
											</group>
										</group>
									</group>
								</group>
								<group
									name="pCylinder8"
									position={[0.371, 4.868, 0.335]}
									rotation={[0, 0, -Math.PI / 2]}
									scale={[0.04, 0.112, 0.04]}>
									<mesh
										name="pCylinder8_plastic_blanc_0"
										geometry={nodes.pCylinder8_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="pCylinder9"
									position={[0.4, 5.33, 0.208]}
									rotation={[0, 0, -Math.PI / 2]}
									scale={[0.04, 0.118, 0.04]}>
									<mesh
										name="pCylinder9_plastic_blanc_0"
										geometry={nodes.pCylinder9_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="pCylinder10"
									position={[0.411, 5.745, 0.065]}
									rotation={[0, 0, -Math.PI / 2]}
									scale={[0.04, 0.114, 0.04]}>
									<mesh
										name="pCylinder10_plastic_blanc_0"
										geometry={nodes.pCylinder10_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="pCylinder11"
									position={[-0.031, 4.868, 0.335]}
									rotation={[0, 0, -Math.PI / 2]}
									scale={[0.04, 0.112, 0.04]}>
									<mesh
										name="pCylinder11_plastic_blanc_0"
										geometry={nodes.pCylinder11_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="pCylinder12"
									position={[-0.055, 5.33, 0.208]}
									rotation={[0, 0, -Math.PI / 2]}
									scale={[0.04, 0.118, 0.04]}>
									<mesh
										name="pCylinder12_plastic_blanc_0"
										geometry={nodes.pCylinder12_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="pCylinder13"
									position={[-0.074, 5.745, 0.065]}
									rotation={[0, 0, -Math.PI / 2]}
									scale={[0.04, 0.114, 0.04]}>
									<mesh
										name="pCylinder13_plastic_blanc_0"
										geometry={nodes.pCylinder13_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="pCube24"
									position={[0.177, -4.973, 0.739]}
									scale={[0.64, 0.036, 0.011]}>
									<mesh
										name="pCube24_plastic_blanc_0"
										geometry={nodes.pCube24_plastic_blanc_0.geometry}
										material={materials.plastic_blanc}
									/>
								</group>
								<group
									name="group10"
									position={[-0.026, 0, 0]}>
									<group
										name="group11"
										position={[0, 0.028, 0.009]}>
										<group
											name="group13"
											position={[-0.005, -0.297, 2.361]}
											rotation={[0.471, 0, 0]}>
											<group
												name="group14"
												position={[0.005, 0, 0]}>
												<group
													name="pSphere12"
													position={[-0.137, -5.077, 0.734]}
													rotation={[Math.PI / 2, 0, 0]}
													scale={0.026}>
													<mesh
														name="pSphere12_trastes_0"
														geometry={nodes.pSphere12_trastes_0.geometry}
														material={materials.trastes}
													/>
												</group>
												<group
													name="pSphere10"
													position={[0.134, -5.077, 0.734]}
													rotation={[Math.PI / 2, 0, 0]}
													scale={0.026}>
													<mesh
														name="pSphere10_trastes_0"
														geometry={nodes.pSphere10_trastes_0.geometry}
														material={materials.trastes}
													/>
												</group>
												<group
													name="pSphere9"
													position={[0.301, -5.077, 0.734]}
													rotation={[Math.PI / 2, 0, 0]}
													scale={0.026}>
													<mesh
														name="pSphere9_trastes_0"
														geometry={nodes.pSphere9_trastes_0.geometry}
														material={materials.trastes}
													/>
												</group>
												<group
													name="pSphere8"
													position={[0.408, -5.077, 0.734]}
													rotation={[Math.PI / 2, 0, 0]}
													scale={0.026}>
													<mesh
														name="pSphere8_trastes_0"
														geometry={nodes.pSphere8_trastes_0.geometry}
														material={materials.trastes}
													/>
												</group>
												<group
													name="pSphere7"
													position={[0.525, -5.077, 0.734]}
													rotation={[Math.PI / 2, 0, 0]}
													scale={0.026}>
													<mesh
														name="pSphere7_trastes_0"
														geometry={nodes.pSphere7_trastes_0.geometry}
														material={materials.trastes}
													/>
												</group>
											</group>
										</group>
									</group>
								</group>
								<group
									name="pCylinder19"
									position={[-0.162, -0.39, 0.744]}
									rotation={[-0.002, 0, 0]}
									scale={[0.882, 0.713, 0.993]}>
									<group name="transform13" />
								</group>
								<group
									name="group12"
									position={[0.456, 1.24, -0.695]}
									scale={0.328}>
									<group
										name="pTorus3"
										position={[-0.006, 4.91, -2.261]}
										rotation={[0, 0.617, 0]}>
										<group name="transform6" />
									</group>
									<group
										name="pTorus2"
										position={[-0.001, 3.86, -2.254]}
										rotation={[0, 0.311, 0]}>
										<group name="transform4" />
									</group>
									<group
										name="pTorus1"
										position={[0, 2.81, -2.251]}>
										<group name="transform5" />
									</group>
								</group>
								<group name="pTorus1_1">
									<group name="transform7" />
								</group>
								<group
									name="pTorus5"
									position={[-0.053, 4.87, -0.115]}
									rotation={[0, 0, -Math.PI / 2]}
									scale={0.008}>
									<group name="transform8" />
								</group>
								<group
									name="pTorus6"
									position={[-0.065, 4.87, -0.115]}
									rotation={[-0.616, 0, -Math.PI / 2]}
									scale={0.008}>
									<group name="transform9" />
								</group>
								<group name="pTorus9">
									<group name="transform11" />
								</group>
								<group
									name="pTorus10"
									position={[-0.025, 3.344, 4.511]}
									rotation={[-1.229, 0, 0]}>
									<group name="transform10" />
								</group>
								<group
									name="pTorus11"
									position={[0.052, 13.409, 2.039]}
									rotation={[-2.918, 0, 0]}
									scale={1.788}>
									<group name="transform12" />
								</group>
								<group name="pCylinder20">
									<mesh
										name="pCylinder20_cordes_0"
										geometry={nodes.pCylinder20_cordes_0.geometry}
										material={materials.cordes}
									/>
								</group>
								<group
									name="pCylinder21"
									position={[0.148, -0.001, 0.003]}>
									<group name="polySurface9">
										<group name="transform16" />
									</group>
									<group
										name="polySurface10"
										position={[-0.005, -0.001, 0.226]}
										rotation={[-0.044, 0.05, 0.011]}>
										<group name="transform15" />
									</group>
									<group name="transform14" />
								</group>
								<group
									name="polySurface11"
									position={[0.122, 0, 0]}>
									<mesh
										name="polySurface11_cordes_0"
										geometry={nodes.polySurface11_cordes_0.geometry}
										material={materials.cordes}
									/>
								</group>
								<group
									name="polySurface12"
									position={[0.238, 0, 0]}
									rotation={[-Math.PI, 0, 0]}
									scale={-1}>
									<mesh
										name="polySurface12_cordes_0"
										geometry={nodes.polySurface12_cordes_0.geometry}
										material={materials.cordes}
									/>
								</group>
								<group
									name="polySurface13"
									position={[0.368, 0, 0]}
									rotation={[-Math.PI, 0, 0]}
									scale={-1}>
									<mesh
										name="polySurface13_cordes_0"
										geometry={nodes.polySurface13_cordes_0.geometry}
										material={materials.cordes}
									/>
								</group>
								<group
									name="pCylinder22"
									position={[0.338, -0.001, 0.003]}
									rotation={[-Math.PI, 0, 0]}
									scale={-1}>
									<mesh
										name="pCylinder22_cordes_0"
										geometry={nodes.pCylinder22_cordes_0.geometry}
										material={materials.cordes}
									/>
								</group>
								<group
									name="group15"
									position={[-0.011, 0, 0]}>
									<group
										name="pSphere11"
										position={[-0.014, -5.125, 0.719]}
										rotation={[2.042, 0, 0]}
										scale={0.026}>
										<mesh
											name="pSphere11_trastes_0"
											geometry={nodes.pSphere11_trastes_0.geometry}
											material={materials.trastes}
										/>
									</group>
									<group name="polySurface9_1">
										<mesh
											name="polySurface9_cordes_0"
											geometry={nodes.polySurface9_cordes_0.geometry}
											material={materials.cordes}
										/>
									</group>
								</group>
								<group
									name="directionalLight1"
									position={[0, 0, 8.557]}
									rotation={[1.341, 0.142, -0.546]}>
									<group
										name="Object_193"
										rotation={[Math.PI / 2, 0, 0]}>
										<group name="Object_194" />
									</group>
								</group>
								<group
									name="areaLight1"
									position={[2.16, 0, -8.761]}
									rotation={[-Math.PI / 2, 0, 0]}>
									<group
										name="Object_196"
										rotation={[Math.PI / 2, 0, 0]}>
										<group name="Object_197" />
									</group>
								</group>
								<group
									name="areaLight2"
									position={[0.427, -9.002, -0.193]}
									rotation={[Math.PI, 0, 0]}>
									<group
										name="Object_199"
										rotation={[Math.PI / 2, 0, 0]}>
										<group name="Object_200" />
									</group>
								</group>
								<group
									name="areaLight3"
									position={[-6.26, -2.579, -9.869]}
									rotation={[-0.456, -0.99, 1.433]}>
									<group
										name="Object_202"
										rotation={[Math.PI / 2, 0, 0]}>
										<group name="Object_203" />
									</group>
								</group>
								<group
									name="areaLight4"
									position={[-10.691, -2.579, -3.384]}
									rotation={[-0.38, -0.481, 1.486]}>
									<group
										name="Object_205"
										rotation={[Math.PI / 2, 0, 0]}>
										<group name="Object_206" />
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('/assets/models/guitarra_2.0.glb')
